spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vizsga
    username: vasi
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop # create, create-drop, update, validate, none
